package com.loomi.order.domain.order.valueobject;

public enum OrderError {
    OUT_OF_STOCK,
    INTERNAL_ERROR,
    WAREHOUSE_UNAVAILABLE,
    ALREADY_OWNED, 
    LICENSE_UNAVAILABLE, 
    DISTRIBUTION_RIGHTS_EXPIRED,
    SUBSCRIPTION_NOT_AVAILABLE,
    SUBSCRIPTION_LIMIT_EXCEEDED,
    DUPLICATE_ACTIVE_SUBSCRIPTION,
    INCOMPATIBLE_SUBSCRIPTIONS,
    PENDING_MANUAL_APPROVAL,
    CREDIT_LIMIT_EXCEEDED,
    INVALID_CORPORATE_DATA,
    PRE_ORDER_SOLD_OUT,
    RELEASE_DATE_PASSED,
    INVALID_RELEASE_DATE
}
