package com.loomi.order_processor.domain.order.dto;

public enum OrderError {
    OUT_OF_STOCK,
    INTERNAL_ERROR,
    WAREHOUSE_UNAVAILABLE,
    ALREADY_OWNED, 
    LICENSE_UNAVAILABLE, 
    DISTRIBUTION_RIGHTS_EXPIRED,
    SUBSCRIPTION_NOT_AVAILABLE,
    SUBSCRIPTION_LIMIT_EXCEEDED,
    DUPLICATE_ACTIVE_SUBSCRIPTION,
    INCOMPATIBLE_SUBSCRIPTIONS,
    PENDING_MANUAL_APPROVAL
}
